# Generated by Django 2.0.9 on 2018-11-27 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('AppointmentsId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('AppointmentsStatus', models.BooleanField()),
                ('date_time', models.DateTimeField()),
                ('totalCost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentId', models.IntegerField()),
                ('text', models.TextField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('ownerId', models.IntegerField(primary_key=True, serialize=False)),
                ('ownerName', models.CharField(max_length=30)),
                ('email', models.TextField(max_length=150)),
                ('phone', models.PositiveIntegerField()),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Salons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saloonName', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('views', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('paybill', models.TextField(blank=True, max_length=12, null=True)),
                ('ownerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hairways.Owners')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('serviceId', models.IntegerField(primary_key=True, serialize=False)),
                ('serviceName', models.CharField(max_length=100)),
                ('serviceCost', models.CharField(max_length=50)),
                ('serviceDuration', models.CharField(max_length=20)),
                ('serviceBookings', models.IntegerField()),
                ('svailability', models.BooleanField(default=True)),
                ('salons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hairways.Salons')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=16)),
                ('last_name', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=16)),
                ('phone', models.IntegerField()),
                ('joined_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.TextField()),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='salons',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hairways.Salons'),
        ),
        migrations.AddField(
            model_name='comments',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hairways.Users'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='salons',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hairways.Salons'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hairways.Services'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hairways.Users'),
        ),
    ]
