# Generated by Django 2.0.9 on 2018-11-22 15:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appoiments',
            fields=[
                ('AppoimentsId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('AppoimentsStatus', models.TextField()),
                ('TotalCost', models.IntegerField()),
                ('UserID', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommentId', models.IntegerField()),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('OwnerId', models.IntegerField(primary_key=True, serialize=False)),
                ('OwnerName', models.TextField()),
                ('Email', models.TextField()),
                ('Phone', models.IntegerField()),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Salons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SaloonName', models.TextField()),
                ('Location', models.TextField()),
                ('Description', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Likes', models.IntegerField()),
                ('Views', models.IntegerField()),
                ('Status', models.BooleanField(default=True)),
                ('Paybill', models.TextField()),
                ('CommentsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hairways.Comments')),
                ('OwnerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hairways.Owners')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('ServiceId', models.IntegerField(primary_key=True, serialize=False)),
                ('ServiceName', models.TextField()),
                ('ServiceCost', models.TextField()),
                ('ServiceDuration', models.TextField()),
                ('ServiceBookings', models.IntegerField()),
                ('Availability', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.TextField()),
                ('Email', models.TextField()),
                ('Phone', models.IntegerField()),
                ('Location', models.TextField()),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hairways.Appoiments')),
            ],
        ),
        migrations.AddField(
            model_name='salons',
            name='ServiceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hairways.Services'),
        ),
        migrations.AddField(
            model_name='salons',
            name='appoinmentsId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hairways.Appoiments'),
        ),
        migrations.AddField(
            model_name='appoiments',
            name='ServicesID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hairways.Services'),
        ),
    ]
