# Generated by Django 2.0.9 on 2018-11-23 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoiments',
            fields=[
                ('AppoimentsId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('AppoimentsStatus', models.BooleanField()),
                ('TotalCost', models.IntegerField()),
                ('UserID', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommentId', models.IntegerField()),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('OwnerId', models.IntegerField(primary_key=True, serialize=False)),
                ('OwnerName', models.CharField(max_length=100)),
                ('Email', models.TextField()),
                ('Phone', models.PositiveIntegerField()),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Salons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SaloonName', models.TextField()),
                ('Location', models.TextField()),
                ('Description', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Likes', models.IntegerField(blank=True, null=True)),
                ('Views', models.IntegerField(blank=True, null=True)),
                ('Status', models.BooleanField(default=True)),
                ('Paybill', models.TextField(blank=True, null=True)),
                ('CommentsId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hairways.Comments')),
                ('OwnerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hairways.Owners')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('ServiceId', models.IntegerField(primary_key=True, serialize=False)),
                ('ServiceName', models.CharField(max_length=100)),
                ('ServiceCost', models.CharField(max_length=50)),
                ('ServiceDuration', models.TextField()),
                ('ServiceBookings', models.IntegerField()),
                ('Availability', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=16)),
                ('phone', models.IntegerField()),
                ('joined_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.TextField()),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='salons',
            name='ServiceId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hairways.Services'),
        ),
        migrations.AddField(
            model_name='salons',
            name='appoinmentsId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hairways.Appoiments'),
        ),
        migrations.AddField(
            model_name='appoiments',
            name='ServicesID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hairways.Services'),
        ),
    ]
