# Generated by Django 2.1.5 on 2019-02-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hairways', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('date_started', models.DateTimeField()),
                ('salary', models.IntegerField()),
                ('favservice', models.CharField(blank=True, max_length=100, null=True)),
                ('favclient', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
