# Generated by Django 2.1.5 on 2019-02-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hairways', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Client',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_student',
            new_name='is_client',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_teacher',
            new_name='is_owner',
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
