# Generated by Django 2.1.5 on 2019-02-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hairways', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
