# Generated by Django 2.1.5 on 2019-02-14 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hairways', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='svailability',
            new_name='availability',
        ),
    ]
