# Generated by Django 2.0.9 on 2018-11-28 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hairways', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('salonId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hairways.Salons')),
            ],
        ),
    ]
