# Generated by Django 2.1.5 on 2019-02-03 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hairways', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productId', models.IntegerField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('product_brand', models.CharField(max_length=100)),
                ('salons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hairways.Salons')),
            ],
        ),
        migrations.AlterField(
            model_name='appointments',
            name='AppointmentsId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
