# Generated by Django 2.1.5 on 2019-02-25 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hairways', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_likes', to='Hairways.Salons')),
            ],
        ),
        migrations.AlterField(
            model_name='appointments',
            name='AppointmentsStatus',
            field=models.BooleanField(default=False),
        ),
    ]
