# Generated by Django 2.1.5 on 2019-02-26 08:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Hairways', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='favservice',
        ),
        migrations.RemoveField(
            model_name='client',
            name='favstaff',
        ),
        migrations.AlterField(
            model_name='staff',
            name='date_started',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
