# Generated by Django 2.1.5 on 2019-02-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hairways', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='services',
        ),
        migrations.AddField(
            model_name='services',
            name='appointments',
            field=models.ManyToManyField(to='Hairways.Appointments'),
        ),
    ]
