# Generated by Django 2.0.9 on 2018-11-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hairways', '0002_auto_20181123_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owners',
            name='Phone',
            field=models.PositiveIntegerField(),
        ),
    ]
