# Generated by Django 2.1.5 on 2019-02-13 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hairways', '0002_user_nickname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Client',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_student',
            new_name='is_client',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_teacher',
            new_name='is_owner',
        ),
    ]
