# Generated by Django 2.1.5 on 2019-02-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hairways', '0002_auto_20190214_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='appointments',
        ),
        migrations.AddField(
            model_name='appointments',
            name='appointments',
            field=models.ManyToManyField(to='Hairways.Services'),
        ),
    ]
