# Generated by Django 2.1.5 on 2019-02-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hairways', '0002_auto_20190214_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salons',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salons',
            name='status',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='salons',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
