# Generated by Django 2.1.5 on 2019-03-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hairways', '0002_auto_20190303_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.PositiveIntegerField(default='0792799958'),
        ),
    ]
