# Generated by Django 2.0.9 on 2018-12-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hairways', '0003_auto_20181201_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=25),
        ),
    ]
