# Generated by Django 2.1.5 on 2019-02-14 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hairways', '0003_auto_20190214_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salons',
            old_name='salonName',
            new_name='salonName',
        ),
    ]
