# Generated by Django 2.1.5 on 2019-02-14 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hairways', '0003_auto_20190214_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='appointments',
            new_name='services',
        ),
    ]
