# Generated by Django 2.1.5 on 2019-06-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hairways', '0003_auto_20190309_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointments',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
