# Generated by Django 2.1.5 on 2019-06-05 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Hairways', '0004_auto_20190605_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
