# Generated by Django 2.1.5 on 2019-01-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hairways', '0004_auto_20181201_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClientSignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=16)),
                ('joined_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='users',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
