# Generated by Django 2.1.5 on 2019-02-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hairways', '0004_auto_20190214_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salons',
            name='shares',
            field=models.IntegerField(default=0),
        ),
    ]
