# Generated by Django 2.1.5 on 2019-01-24 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hairways', '0005_auto_20190121_1536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientLogin',
        ),
        migrations.DeleteModel(
            name='ClientSignUp',
        ),
        migrations.AddField(
            model_name='salons',
            name='Owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
