# Generated by Django 2.1.5 on 2019-02-14 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hairways', '0005_appointments_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='user',
            new_name='client',
        ),
    ]
