# Generated by Django 2.1.5 on 2019-01-25 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hairways', '0005_auto_20190121_1536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientLogin',
        ),
        migrations.DeleteModel(
            name='ClientSignUp',
        ),
    ]
