# Generated by Django 2.1.5 on 2019-06-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hairways', '0005_appointments_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
    ]
