# Generated by Django 2.1.5 on 2019-02-15 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hairways', '0006_auto_20190214_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(default='myemail@gmail.com', max_length=30),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
