# Generated by Django 2.1.5 on 2019-06-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hairways', '0006_appointments_is_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
