# Generated by Django 2.1.5 on 2019-02-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hairways', '0006_auto_20190125_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='salons',
            name='replies',
            field=models.TextField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salons',
            name='shares',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
