# Generated by Django 2.1.5 on 2019-02-02 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hairways', '0007_auto_20190202_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='text',
        ),
        migrations.RemoveField(
            model_name='salons',
            name='replies',
        ),
        migrations.AddField(
            model_name='comments',
            name='replies',
            field=models.TextField(default=50, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='salons',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Hairways.Salons'),
        ),
    ]
