# Generated by Django 2.1.5 on 2019-02-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hairways', '0008_auto_20190202_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='replies',
            new_name='reply',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='salons',
            new_name='salon',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='commentId',
        ),
        migrations.AddField(
            model_name='comments',
            name='author',
            field=models.CharField(default=50, max_length=200),
            preserve_default=False,
        ),
    ]
