# Generated by Django 2.1.5 on 2019-02-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hairways', '0008_auto_20190219_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salons',
            old_name='saloonName',
            new_name='salonName',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='svailability',
            new_name='availability',
        ),
        migrations.AlterField(
            model_name='salons',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salons',
            name='shares',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salons',
            name='status',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='salons',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
