# Generated by Django 2.2.3 on 2019-08-01 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190731_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salons',
            old_name='salonName',
            new_name='name',
        ),
    ]
