# Generated by Django 2.2.3 on 2019-08-01 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190801_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salons',
            name='likes',
        ),
        migrations.AddField(
            model_name='salons',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Preference',
        ),
    ]
