# Generated by Django 2.2.3 on 2019-08-02 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190801_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='nickname',
            new_name='Full_Name',
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='client', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
