# Generated by Django 2.2.3 on 2019-08-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190802_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='salons',
            name='url',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
