# Generated by Django 2.2.3 on 2019-08-02 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_salons_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Salons',
            new_name='Salon',
        ),
    ]
