# Generated by Django 2.2.3 on 2019-08-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190802_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='reply',
        ),
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.TextField(default=5),
            preserve_default=False,
        ),
    ]
